const p = 3.14;
const e = 2.71;
var name = "Sahil Rajwar";
let age = 18;
const is_male = true;
console.log(typeof(p));
console.log(typeof(e));
console.log(typeof(name));
console.log(typeof(age));
console.log(typeof(is_male));
